language: go
sudo: false

matrix:
  include:
    # "1.x" always refers to the latest Go version, inc. the patch release.
    # e.g. "1.x" is 1.12 until 1.12.1 is available.
    - go: 1.x
      env: LATEST=true
    - go: 1.12.x
    - go: tip
  allow_failures:
    - go: tip

before_script:
  - go vet ./...

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
